### ISSUE TITLE
Inconsistent logo

### ISSUE THREAD

**Issue by zachlatta** [hackedu/website#100]
![tmp](https://cloud.githubusercontent.com/assets/992248/7887836/e9e394aa-05e8-11e5-8523-5f145aaf596e.png)

This is with #98 merged. It'd be great if we could use the same logo throughout the entire site.

**Comment by zachlatta** [comment]
Actually not sure what happened here, seems to now be good.

![tmp](https://cloud.githubusercontent.com/assets/992248/7888224/c6289864-05eb-11e5-946b-58d8ae9699c5.png)

**Comment by MaxWofford** [comment]
Woah, you changed your avatar. That freaked me out.

**Comment by zachlatta** [comment]
I try my best :-P.
