### ISSUE TITLE
Add our funders

### ISSUE THREAD

**Issue by jonleung** [hackedu/website#102]
- The Reva and David Logan Foundation: http://www.loganfdn.org/
- @zachlatta , can you ask our other donors if they would be comfortable with us publically mentioning their name on our website?

@zachlatta, assign this task to Max after you've confirmed all donors.

**Comment by zachlatta** [comment]
Will have to check on this later---do start with putting the Logan
Foundation up for now though.

**Comment by zachlatta** [comment]
Mockup of format:

![mockup](https://cloud.githubusercontent.com/assets/992248/8014112/cca8b39e-0b82-11e5-8487-c7589c7c844a.png)

**Comment by MaxWofford** [comment]
:+1:
