### ISSUE TITLE
Add donations page description

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/website#108]
From Suzan:
`This one takes some thought, but should be done soon: on your "donate" page there is no text that explains why you need donations or how they will be used.  It would be a good idea to add some text up top  to engage, inform and appreciate your potential donors. `

**Comment by zachlatta** [comment]
Totally agree. I think something akin to Codestarter's donate page (https://codestarter.org/pledge) may make a lot of sense. We'll need our own formatting/messaging, of course.

**Comment by MaxWofford** [comment]
Closing this for the time being because donations are not a focus of our current goals.
