### ISSUE TITLE
"As seen in X publications"

### ISSUE THREAD

**Issue by zachlatta** [hackedu/website#114]
Mention that we've been mentioned in the following publications:

* EdSurge
* USA Today
* California Sunday

Maybe something like this, where the text with the publication's name is their logo?

![as_seen_in](https://cloud.githubusercontent.com/assets/992248/8071414/94a688ba-0ebe-11e5-8f29-00f7ef91379f.png)

The background could be dark grey and the logos could be a slightly lighter grey. Maybe like the following, but less bad looking:

![as_seen_in_2](https://cloud.githubusercontent.com/assets/992248/8071462/09f36016-0ebf-11e5-8c90-01822b6ea15a.png)

**Comment by MaxWofford** [comment]
@zachlatta big fan of the darker theme.

**Comment by MaxWofford** [comment]
@zachlatta Can I get links to each of the articles?

**Comment by zachlatta** [comment]
- EdSurge: https://www.edsurge.com/n/2015-06-05-raise-a-glass-it-s-now-possible-to-become-a-thiel-fellow-and-legally-drink
- USA Today: http://www.usatoday.com/story/tech/2015/06/01/young-developers-create-apple-apps/28302657/
- California Sunday: https://stories.californiasunday.com/2015-06-07/real-teenagers-silicon-valley

**Comment by zachlatta** [comment]
Any updates on this?

**Comment by MaxWofford** [comment]
![screenshot 2015-08-09 at 9 14 28 pm](https://cloud.githubusercontent.com/assets/5891442/9159352/ab5d76b6-3edb-11e5-984c-3160eca23bca.png)
Content is there, but unstyled.

**Comment by zachlatta** [comment]
Which branch is this on? I may just add to it directly.

On Sun, Aug 9, 2015 at 9:15 PM, Max Wofford <notifications@github.com>
wrote:

> [image: screenshot 2015-08-09 at 9 14 28 pm]
> <https://cloud.githubusercontent.com/assets/5891442/9159352/ab5d76b6-3edb-11e5-984c-3160eca23bca.png>
> Content is there, but unstyled.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/website/issues/114#issuecomment-129293992>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Actually, is there an open PR for this?

On Sun, Aug 9, 2015 at 9:19 PM, Zach Latta <zach@hackedu.us> wrote:

> Which branch is this on? I may just add to it directly.
>
> On Sun, Aug 9, 2015 at 9:15 PM, Max Wofford <notifications@github.com>
> wrote:
>
>> [image: screenshot 2015-08-09 at 9 14 28 pm]
>> <https://cloud.githubusercontent.com/assets/5891442/9159352/ab5d76b6-3edb-11e5-984c-3160eca23bca.png>
>> Content is there, but unstyled.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/hackedu/website/issues/114#issuecomment-129293992>.
>>
>
>
>
> --
> Zach Latta
> hackEDU | zach@hackedu.us
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by MaxWofford** [comment]
@zachlatta the `add-publications` branch.

**Comment by hellyeah** [comment]
standup: done by the weekend

**Comment by MaxWofford** [comment]
Here is the current version. The middle image is being hovered over (my mouse is invisible in the screenshot)

![screenshot 2015-08-18 at 3 45 09 pm](https://cloud.githubusercontent.com/assets/5891442/9344807/398ecddc-45c0-11e5-889f-f45abec0729d.png)

**Comment by zachlatta** [comment]
Looks good! I left a comment in #136 about logos.

On Tue, Aug 18, 2015 at 3:46 PM, Max Wofford <notifications@github.com>
wrote:

> Here is the current version. The middle image is being hovered over (my
> mouse is invisible in the screenshot)
>
> [image: screenshot 2015-08-18 at 3 45 09 pm]
> <https://cloud.githubusercontent.com/assets/5891442/9344807/398ecddc-45c0-11e5-889f-f45abec0729d.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/website/issues/114#issuecomment-132379792>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Closed by #136.
