### ISSUE TITLE
Add comparison metrics

### ISSUE THREAD

**Issue by zachlatta** [hackedu/website#132]
Add comparison metrics to the "Our Impact" section below our stats.

The comparisons we want to add:

- 32% women
  - 18.6% of AP CS test takers are female
- 37% black/Hispanic
  - 11.7% of AP CS test takers are black or Hispanic

Source: http://home.cc.gatech.edu/ice-gt/556

![website 132-comparison-metrics](https://cloud.githubusercontent.com/assets/992248/8487409/cd70811e-20c0-11e5-8b87-caabdbc05d4f.png)

**Comment by hellyeah** [comment]
standup: done by weekend

**Comment by MaxWofford** [comment]
![screenshot 2015-08-18 at 3 45 52 pm](https://cloud.githubusercontent.com/assets/5891442/9345236/bad9ed38-45c3-11e5-85a1-25fbb0579f7e.png)
This looks kinda funny because the comparison breaks the flow of the regular metric.

**Comment by MaxWofford** [comment]
![screenshot 2015-08-18 at 4 10 55 pm](https://cloud.githubusercontent.com/assets/5891442/9345305/57c31c78-45c4-11e5-847f-dfae2480dcda.png)
How's this?

**Comment by zachlatta** [comment]
For the minorities in tech metric, can you use the industry stats instead of what we see in high school?

**Comment by zachlatta** [comment]
So X% of software engineers in industry are black/Hispanic.

**Comment by zachlatta** [comment]
Let's track the progress for completing this issue in the PR for it in #142.

On Tue, Aug 18, 2015 at 4:15 PM, Max Wofford <notifications@github.com>
wrote:

> [image: screenshot 2015-08-18 at 4 10 55 pm]
> <https://cloud.githubusercontent.com/assets/5891442/9345305/57c31c78-45c4-11e5-847f-dfae2480dcda.png>
> How's this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/website/issues/132#issuecomment-132388173>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by zachlatta** [comment]
Closed by #142.
