### ISSUE TITLE
Add number of states and schools to "Our Impact" section

### ISSUE THREAD

**Issue by zachlatta** [hackedu/website#133]
It'd be great if we could add the number of schools and states we're in to the "Our Impact" section.

Stats:

- 40 schools
- 11 states

**Comment by MaxWofford** [comment]
Not sure if we want that in the `impact` section. It seems like this is more impressive to see visually on the map. It just means we need to update the map.

**Comment by zachlatta** [comment]
I agree that it's certainly more visually impressive to see it on the map,
but I do think it's important to have the numbers listed out on the page
itself (especially for the people who are only skimming the website).
Thoughts?

On Tue, Aug 18, 2015 at 6:07 PM, Max Wofford <notifications@github.com>
wrote:

> Not sure if we want that in the impact section. It seems like this is
> more impressive to see visually on the map. It just means we need to update
> the map.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/website/issues/133#issuecomment-132407934>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by MaxWofford** [comment]
@zachlatta That makes sense. I guess I'm just worried the impact section will get cluttered.

**Comment by MaxWofford** [comment]
![screenshot 2015-08-18 at 5 04 46 pm](https://cloud.githubusercontent.com/assets/5891442/9348722/e4ef1ebe-45ef-11e5-92a1-1bafb2595b9b.png)

**Comment by zachlatta** [comment]
Good enough for me. Can you submit a PR?
