### ISSUE TITLE
Create mockup of homepage redesign

### ISSUE THREAD

**Issue by zachlatta** [hackedu/website#137]
Create an image mockup (Illustrator/Photoshop/etc) of a redesign of the https://hackedu.us homepage.

Moved from hackedu/meta#91.

**Comment by zachlatta** [comment]
Closing due to @andreadeng starting school.

**Comment by MaxWofford** [comment]
![screenshot 2015-08-24 at 2 09 38 pm](https://cloud.githubusercontent.com/assets/5891442/9452560/c6541a30-4a69-11e5-9059-626614460d0c.png)
wat

**Comment by zachlatta** [comment]
Holy bug batman!

On Mon, Aug 24, 2015 at 2:09 PM, Max Wofford <notifications@github.com>
wrote:

> [image: screenshot 2015-08-24 at 2 09 38 pm]
> <https://cloud.githubusercontent.com/assets/5891442/9452560/c6541a30-4a69-11e5-9059-626614460d0c.png>
> wat
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/website/issues/137#issuecomment-134381001>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us
