### ISSUE TITLE
Fix our impact section to be friendly on all screen sizes

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/website#138]
![screenshot 2015-07-27 at 8 15 23 am](https://cloud.githubusercontent.com/assets/5891442/8909719/c811ff9c-3437-11e5-9865-8d6fc5e8bf6d.png)

**Comment by zachlatta** [comment]
:+1:

--
Zach Latta
Executive Director of hackEDU <https://hackedu.us>
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta
