### ISSUE TITLE
Olark IRC chat on hackEDU website

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/website#164]
Transferred from hackedu/meta#128

@jonleung something we can iframe that looks really pretty

First idea:
iframe embed

**Comment by ZucchiniZe** [comment]
I would suggest using something like kiwiirc because you can easily make them join a chanel with a predefined nickname automatically, e.g. https://kiwiirc.com/client/irc.freenode.net/?nick=Hacker|?#hackedu

**Comment by zachlatta** [comment]
It's also possible to set up freenode webchat with a predefined channel and
nickname (https://webchat.freenode.net/).

On Wed, Sep 23, 2015 at 9:51 AM, Alex B <notifications@github.com> wrote:

> I would suggest using something like kiwiirc because you can easily make
> them join a chanel with a predefined nickname automatically, e.g.
> https://kiwiirc.com/client/irc.freenode.net/?nick=Hacker|?#hackedu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/website/issues/164#issuecomment-142659970>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by ZucchiniZe** [comment]
That is exactly what kiwiirc does, but with a better ui.

**Comment by jonleung** [comment]
^ :+1:

**Comment by MaxWofford** [comment]
Closing this from https://github.com/hackedu/website/commit/28a2d2b38e4f3edabdd45f8d4b28fa0ccb2f0517
