### ISSUE TITLE
Website feedback from Sooz

### ISSUE THREAD

**Issue by jonleung** [hackedu/website#170]
We had some website feedback from Sooz:

![image](https://cloud.githubusercontent.com/assets/654941/9969157/b6164638-5e01-11e5-8de1-5c378ae9a407.png)

Let's turn these into actual issues that are actionable.

**Comment by MaxWofford** [comment]
@jonleung I'm confused. Was I assigned to create issues for this?

**Comment by jonleung** [comment]
@MaxWofford, yes if that's ok /  you decide it is important enough.

Context: I was given this feedback and didn't have time to make detailed enough issues for what needed to be fixed. Therefore, I am essentially just passing that feedback to you and letting you decide if you want to act on it.

**Comment by zachlatta** [comment]
Might this be better in a PM? I'm not super sure what this issue entails
just from seeing that screenshot without context (especially the bit about
the photo of Max).

On Sat, Sep 19, 2015 at 8:58 PM, Jonathan Leung <notifications@github.com>
wrote:

> @MaxWofford <https://github.com/MaxWofford>, yes if that's ok / you
> decide it is important enough.
>
> Context: I was given this feedback and didn't have time to make detailed
> enough issues for what needed to be fixed. Therefore, I am essentially just
> passing that feedback to you and letting you decide if you want to act on
> it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/website/issues/170#issuecomment-141743343>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by jonleung** [comment]
@zachlatta, yeah that's all the context I have. Closing this issue for now because it seems like we don't have enough information to proceed and I don't have the bandwidth to investigate more.
