### ISSUE TITLE
Randomize header image on load

### ISSUE THREAD

**Issue by zachlatta** [hackedu/website#40]
It might be cool to randomly put a different header image on every page refresh with different pictures of our leaders/members.

Thoughts @maxwofford?

**Comment by MaxWofford** [comment]
That's a good idea! Do you have any particular images in mind?

**Comment by MaxWofford** [comment]
The current image looks so good/photogenic it feel fake. Maybe we could also tag the people with links to their github profiles?

**Comment by zachlatta** [comment]
Any suggestions for how we could tag them?

**Comment by zachlatta** [comment]
Closing for now - if anyone wants to see this happen, please feel free to reopen!
