### ISSUE TITLE
hackEDU logo is in different fonts on different areas of the page

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/website#41]

**Comment by MaxWofford** [comment]
![hack](https://cloud.githubusercontent.com/assets/5891442/6154142/470cfa54-b1de-11e4-98ba-2a004ca615e8.png) Not sure if it looks any better. Thoughts?

**Comment by MaxWofford** [comment]
Closed by PR#45

**Comment by zachlatta** [comment]
Yeah, this should be better.

**Comment by MaxWofford** [comment]
The 'h' is unusually bold on 'hackEDU'

**Comment by zachlatta** [comment]
This is due to using two different fonts for the logo. A potential
solution would be to modify the Open Sans font and change the `h` to
something along the lines of Amaranth's `h`.

--
Zach Latta
http://zachlatta.com
https://github.com/zachlatta
https://twitter.com/zachlatta
