### ISSUE TITLE
create a page with sponsors

### ISSUE THREAD

**Issue by zachlatta** [hackedu/website#53]
Create a page on the site with all of our sponsors' logos.

This might make more sense to put directly on the homepage.

Our sponsors are:

* CodeHS
* Nitrous.io
* Make School
* Rackspace
* Hack Reactor
* Workflowy
* First Code Academy
* Taplytics
* Sourcegraph

Remind me and I'll send you their logos.

**Comment by zachlatta** [comment]
@MaxWofford can you add First Code Academy and Taplytics to the page as well?

**Comment by zachlatta** [comment]
Also, please make sure all of the sponsor logos are linked.

**Comment by zachlatta** [comment]
@MaxWofford just added Sourcegraph to the list as well.

**Comment by zachlatta** [comment]
Closing this for the time being...

**Comment by zachlatta** [comment]
Take that back, assigned an issue to @MaxWofford on Asana to take care of this.

**Comment by zachlatta** [comment]
@MaxWofford what's the status on this?

**Comment by MaxWofford** [comment]
@zachlatta ready for merge https://github.com/hackedu/hackedu/pull/73
