### ISSUE TITLE
Indicate how long a semester actually is.

### ISSUE THREAD

**Issue by jonleung** [hackedu/website#56]
On the sponsorship page, it is not clear that they are sponsoring hackEDU for a semester. Right now that means that they will be sponsoring until August 2015. The sponsorship  page should indicate that  sponsorship are for the the semester.

**Comment by zachlatta** [comment]
Where should we indicate this?

**Comment by jonleung** [comment]
@zachlatta on the sponsorship page?

**Comment by zachlatta** [comment]
Gotcha, gotcha. Wasn't clear in the original issue.

**Comment by MaxWofford** [comment]
@zachlatta @jonleung Closing this until we have immediate need for the sponsor page.

**Comment by zachlatta** [comment]
:+1:
