### ISSUE TITLE
Shorten the tagline so it doesn't have high schoolers twice

### ISSUE THREAD

**Issue by jonleung** [hackedu/website#59]
Shorten to:

hackEDU empowers students to build things they care about by creating, connecting, and growing student-run coding clubs in high school .

**Comment by zachlatta** [comment]
I really prefer "through" in place of "by". Other than that, looks
great!

**Comment by MaxWofford** [comment]
Going with `by`:
https://english.stackexchange.com/questions/25459/what-general-rules-govern-the-usage-of-by-versus-through

**Comment by zachlatta** [comment]
How about:

hackEDU empowers high school students to build things they care about through creating, connecting, and growing after school programming clubs.

**Comment by zachlatta** [comment]
Accidentally closed the issue.

**Comment by MaxWofford** [comment]
Think this should stay `by`. [Source](https://english.stackexchange.com/questions/25459/what-general-rules-govern-the-usage-of-by-versus-through)

**Comment by zachlatta** [comment]
I concede defeat.

**Comment by zachlatta** [comment]
What if we did:

hackEDU empowers high school students to build things they care about by creating, connecting, and growing after school programming clubs.

**Comment by MaxWofford** [comment]
This misses out on student-run clubs.

**Comment by MaxWofford** [comment]
Though I really like how you wrote it. What about: hackEDU empowers high school students to build things they care about by creating, connecting, and growing student-run programming clubs.

**Comment by zachlatta** [comment]
sure! i like it. @jonleung thoughts?

**Comment by MaxWofford** [comment]
@jonleung @zachlatta How do you feel about the bolding here?
![hackedutest](https://cloud.githubusercontent.com/assets/5891442/6609047/5c4984a4-c80a-11e4-8d6d-004152c6d310.png)

**Comment by zachlatta** [comment]
Thoughts on changing "they care about" to "they are excited about"? Also, what if we changed "programming clubs" to "coding clubs".

What does it look like with "to build things they are excited about" bolded?

**Comment by MaxWofford** [comment]
How does this look?
![adwadw](https://cloud.githubusercontent.com/assets/5891442/6633605/5cc669e8-c908-11e4-9abb-2d3ecf65aea4.png)

**Comment by zachlatta** [comment]
:thumbsup:

**Comment by MaxWofford** [comment]
This was fixed a while ago.

**Comment by zachlatta** [comment]
:+1:
