### ISSUE TITLE
Add that we are a 501c3 with our Tax id. See how Bayes impact did it (search for "2015 Bayes Impact, 501"

### ISSUE THREAD

**Issue by jonleung** [hackedu/website#75]
See http://www.bayesimpact.org

**Comment by zachlatta** [comment]
Can you add Mission Bit's EIN here? If we're going to publicly display it on our website, we can have it in a GitHub issue.

**Comment by jonleung** [comment]
@zachlatta, I lost track of what the EIN is...

**Comment by zachlatta** [comment]
46-0945785
