### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by zachlatta** [hackedu/website#79]
@MaxWofford @benzweig

Create basic sitemap (userflow) on draw.io

EDIT: add description -@MaxWofford

**Comment by zachlatta** [comment]
@MaxWofford is there a deliverable for this?

**Comment by MaxWofford** [comment]
Oh, yes. I'll add a comment before closing issues next time.

**Comment by zachlatta** [comment]
Ideally the issue would be resolved by a PR, correct?

**Comment by MaxWofford** [comment]
The sitemap was a brainstorming tool for deciding content on the new iteration for the website; it shouldn't be in the code.

**Comment by zachlatta** [comment]
What's the disadvantage of having it in the code? Would be great if our
brainstorming was open as well :-).

**Comment by MaxWofford** [comment]
That's a good point :+1:! I'll reopen this until I submit a PR.

**Comment by zachlatta** [comment]
:shipit:

**Comment by MaxWofford** [comment]
Website redesign is on hold until @benzweig is out of school

**Comment by zachlatta** [comment]
:+1:
