### ISSUE TITLE
Rough styleguide

### ISSUE THREAD

**Issue by zachlatta** [hackedu/website#80]
Make an internal styleguide for reference while designing the new iteration of the website.(@benzweig @MaxWofford) 

EDIT: Added description @MaxWofford

**Comment by MaxWofford** [comment]
Description: Make an internal styleguide for reference while designing the new iteration of the website. 

@benzweig How's this?

**Comment by zachlatta** [comment]
Feel free to go ahead and edit the main issue. At the bottom just add a
quick note saying something like "edited by @maxwofford" or something so
people know it was changed since I created the issue.

**Comment by MaxWofford** [comment]
Website redesign is on hold until after @benzweig get out of school
