### ISSUE TITLE
Place to list deals that hackedu students get

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/website#81]
It would be awesome to have an area so students can get access to stuff like twilio's free credits

**Comment by MaxWofford** [comment]
RescueTime gave us a similar deal too.

**Comment by zachlatta** [comment]
Perhaps a private repo that all club leaders are added to with all this
stuff in the README?

**Comment by zachlatta** [comment]
Could call the repo `goodies` :-p

**Comment by MaxWofford** [comment]
:+1: for private repo.

Maybe this gives us an excuse to build a student portal for the website redesign?

**Comment by zachlatta** [comment]
Perhaps? Student portal sounds like a lot of work for information that
can be put into a text file. Maybe when we have more in-depth
partnerships worked out where we can automatically provision accounts
for people?

**Comment by MaxWofford** [comment]
Sounds good! I'll make a repo for this when I get back from the club meeting.

**Comment by zachlatta** [comment]
I think we still need to get private repos from GitHub. @jonleung what's
the status on zachlatta/fundraising#6?

**Comment by MaxWofford** [comment]
Closing this until we have issues with https://github.com/MaxWofford/hackedu-deals

**Comment by zachlatta** [comment]
@jonleung what's the status on GitHub donating private repos to us? It'd
be great if we could have these private repos in the org instead of our
private profiles.
