### ISSUE TITLE
Add 'how did you hear about us' to sign-up form

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/website#86]
This could help us understand where our inbound is coming from.

**Comment by zachlatta** [comment]
Would this be a text field? What if we asked this during the first call?
Might come off as not very personable.

**Comment by zachlatta** [comment]
* Might come off as not very personable if it's just a text field.

**Comment by MaxWofford** [comment]
During the call would be much more personal :+1:. We can record this data in the calc.hackedu.us spreadsheet. Should we put general call guidelines in a repo?

**Comment by zachlatta** [comment]
Sure! As long as you plan to maintain the file. Would probably be best in https://github.com/hackedu/meta.

Closing for now.

**Comment by zachlatta** [comment]
Perhaps we could have the spreadsheet stored in https://github.com/hackedu/meta as well?
