### ISSUE TITLE
Add a tab for IRC in our website where the "projects" tab is

### ISSUE THREAD

**Issue by jonleung** [hackedu/website#87]
We can use https://kiwiirc.com/embedding to easily embed an IRC client. Just ask the person for their name in a javascript "prompt("What is your name") box and then load the iframe. It will be janky but at least it will work!

**Comment by jonleung** [comment]
@MaxWofford, seems like we just put in an iFrame like this: http://jsbin.com/tajetidizu/1/edit?html,output, we don't even need the confirm box

**Comment by zachlatta** [comment]
will this really help facilitate communication? an iframe to chat on our website may be unintuitive/ugly. perhaps a link to freenode web chat for #hackedu would be nicer?

**Comment by MaxWofford** [comment]
:+1: a nav button- It would look unobtrusive.

**Comment by zachlatta** [comment]
@MaxWofford do you mean a nav button that redirects to our team chat? i feel like that'd be confusing to the user and may be better suited to the footer (especially for nontechnical folk).

**Comment by MaxWofford** [comment]
@zachlatta We already have a link to IRC in our footer:
![screenshot 2015-04-27 at 7 20 12 am](https://cloud.githubusercontent.com/assets/5891442/7349437/dffc8ed2-ecad-11e4-923a-aabca7da2ed1.png)

**Comment by jonleung** [comment]
@zachlatta @MaxWofford,

Just linking to freenode is not intuitive, people don't know which channel to join, I think Kiwi is better, we can table this till later.

**Comment by zachlatta** [comment]
What do you mean? It links to the freenode web chat.

![recorded](https://cloud.githubusercontent.com/assets/992248/7416554/1d7900c4-ef15-11e4-9404-98a8f00d073f.gif)

**Comment by MaxWofford** [comment]
@jonleung Does Kiwi let you view the chat without setting a nickname?

**Comment by zachlatta** [comment]
It doesn't. You'd need to have a bot in the channel logging the chat to see it without joining. You can look at https://botbot.me/freenode/hackedu/ to get realtime logs from the o__o bot in the channel.

**Comment by MaxWofford** [comment]
Cool, how about the irc links to https://botbot.me/freenode/hackedu/?

Thoughts @jonleung @zachlatta?

**Comment by zachlatta** [comment]
Hmm, I think it'd be nice if we linked directly to the freenode web chat
so they can immediately join our chat. If they join the chat through the
freenode web interface, they'll also see a link to our logs if they want
to view them.

--
Zach Latta Executive Director of hackEDU[1] http://zachlatta.com
https://github.com/zachlatta https://twitter.com/zachlatta


On Sun, May 3, 2015, at 06:42 PM, Max Wofford wrote:
> Cool, how about the irc links to https://botbot.me/freenode/hackedu/?


> Thoughts @jonleung[2] @zachlatta[3]?


> — Reply to this email directly or view it on GitHub[4].

>



Links:

  1. https://hackedu.us/
  2. https://github.com/jonleung
  3. https://github.com/zachlatta
  4. https://github.com/hackedu/website/issues/87#issuecomment-98565352

**Comment by MaxWofford** [comment]
Closing this because already implemented.
