### ISSUE TITLE
define "hacker" + larger vision (enabling people who build stuff)

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/website#94]
More explicitly defining these things may help general-knowledge viewers understand our program.

**Comment by MaxWofford** [comment]
@zachlatta @jonleung Thoughts on adopting another term (maker, builder, etc.)?

**Comment by zachlatta** [comment]
I'd really like to stick with hacker (I think it falls into the broader
hack branding), but agree we should define it.

**Comment by MaxWofford** [comment]
@zachlatta I think we should stay with "hacker" for the foreseeable future, because we are already branded with it. There are some drawbacks and implied exclusions to the word (excluding non-programmer hackers) that we should be aware of going into this.

(default use of the word "hacker" = programming hacker, whereas hardware hacker is explicit)

**Comment by zachlatta** [comment]
Yup, agreed. I want to do a hostile takeover of the word. We should be
careful of excluding non-programming hackers, but I think we can broaden
the definition.

**Comment by zachlatta** [comment]
*broaden the definition so both programming and hardware hackers fall
under the same definition

**Comment by MaxWofford** [comment]
Thinking of defining hacker straight on the front page. Could I get some feedback on this:
hacker \ˈha-kər\ n.
A person who engages in an activity without needing talent or skill. They are able to learn as they go by tinkering with things around them.

**Comment by zachlatta** [comment]
What about:

Hacker - someone who creates what they see missing in the world and isn't afraid to break the status quo

**Comment by MaxWofford** [comment]
`isn't afraid to break the status quo` sounds kind of aggressive. Like hackers go to the point of doing it constantly just for fun. We should also be careful of using keywords like `break`; this may trigger people thinking about the old definition.
