### ISSUE TITLE
"interested in sponsoring/donating?" button

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/website#95]
We still don't have an easy way for people to donate to us.

**Comment by MaxWofford** [comment]
@zachlatta is Stripe a good way to process non-profit donations?

**Comment by zachlatta** [comment]
I've set up https://donate.hackedu.us which redirects to a PayPal link. We can also set up a donate page with Stripe on the homepage. I'll shoot them an email to see if they'll donate their service to us.

**Comment by zachlatta** [comment]
Okay, sent Stripe an email asking for no transaction fee.

**Comment by MaxWofford** [comment]
Awesome! Thanks @zachlatta. For the time being, I'll add a donation button on the home page and link it to the donate subdomain. I'll update this when we hear back from Stripe.

**Comment by zachlatta** [comment]
Sounds good.

**Comment by zachlatta** [comment]
Still waiting on a response, followed up twice now.

**Comment by MaxWofford** [comment]
@zachlatta Sorry, I'm not clear on that. Response to what?

**Comment by zachlatta** [comment]
Should have clarified, sorry about that! Still waiting on a response from the person I emailed at Stripe asking for free transactions.

**Comment by MaxWofford** [comment]
@zachlatta Any updates on this?

**Comment by zachlatta** [comment]
Yeah, Stripe has given us a fair amount of credit. Before working on this,
coordinate with me to discuss what it should look like.

On Fri, Sep 11, 2015 at 11:08 AM, Max Wofford <notifications@github.com>
wrote:

> @zachlatta <https://github.com/zachlatta> Any updates on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hackedu/website/issues/95#issuecomment-139615860>.
>



-- 
Zach Latta
hackEDU | zach@hackedu.us

**Comment by MaxWofford** [comment]
Sounds good!

**Comment by MaxWofford** [comment]
Closing this for the time being because donations are not a focus of our current goals.
