### ISSUE TITLE
"Team" bios and contact info

### ISSUE THREAD

**Issue by MaxWofford** [hackedu/website#96]
This could help prevent the emails addressed to @zachlatta going to team@hackedu.us

**Comment by zachlatta** [comment]
100% agreed, what if we did cards for these?

Something like this:



Could maybe do some sort of description of the person when you hover
over their image or put a description under the picture and above
the email.

**Comment by zachlatta** [comment]
100% agreed, what if we did cards for these?

Something like this:

![mockup](https://cloud.githubusercontent.com/assets/992248/7887762/501fa89a-05e8-11e5-8913-7268321f64ea.png)

Could maybe do some sort of description of the person when you hover
over their image or put a description under the picture and above
the email.

**Comment by MaxWofford** [comment]
@zachlatta I like that idea. Just curious, what did you make that image in?

**Comment by zachlatta** [comment]
https://balsamiq.com/products/mockups/

**Comment by zachlatta** [comment]
What if we did something like the following?

![mockup](https://cloud.githubusercontent.com/assets/992248/8011941/1fb7bece-0b72-11e5-8a33-2afb7f803074.png)

**Comment by zachlatta** [comment]
Closed by #113.
