### ISSUE TITLE
Add In Kind Sponsors Logos to Website

### ISSUE THREAD

**Issue by jonleung** [hackedu/website#99]
- [x] Add CloudApp's Logo ([link to presskit](http://getcloudapp.com/help/presskit))
- [ ] Add Bee's Logo ([link to presskit](http://bee-app.s3.amazonaws.com/public/bee-press-kit.zip))
- [x] Add Expensify Logo ([link to presskit](http://we.are.expensify.com/press/))
- [ ] Add Airtable's Logo ([just use their website image](https://airtable.com/))

**Comment by zachlatta** [comment]
Let's make these logos relatively small, maybe we should decrease the
size of all logos. Don't want them to take up too much space on the
homepage. Maybe we could move all of our sponsor logos to
https://hackedu.us/sponsor or something as well.

**Comment by zachlatta** [comment]
*https://hackedu.us/sponsors

**Comment by jonleung** [comment]
Thanks so much @baz forgiving us a copy of Bee! I absolutely love it! We're going to add these as soon as possible!

**Comment by MaxWofford** [comment]
Thoughts on making a model for these sponsors. This is starting to take a long time, and we're adding ~1 every week or so.

**Comment by zachlatta** [comment]
What if we set the precedent that the person who secures the sponsor is responsible for submitting the PR?

**Comment by MaxWofford** [comment]
I'd be down for it. Even more reason to make a model for it.
@jonleung Thoughts?

**Comment by jonleung** [comment]
@MaxWofford @zachlatta happy with what we discussed last night with sending URLs of images to max.

**Comment by zachlatta** [comment]
Cool, @jonleung can you update this PR with links to images or attach the images directly?

**Comment by jonleung** [comment]
@zachlatta @MaxWofford I don't think I have the bandwidth to get direct images for these but will in the future. @MaxWofford is that ok?

**Comment by zachlatta** [comment]
Wasn't able to get a solid logo for Airpair (they have a little icon on their site, but it's only ~32px wide). Bee's logo is really tall and requires much more work to make look decent on our site. Leaving those two out for now.

**Comment by MaxWofford** [comment]
@jonleung @zachlatta It sounds like there aren't any actionable outcomes left to this. Can we close this?

**Comment by zachlatta** [comment]
I'm okay with this, @jonleung?

**Comment by zachlatta** [comment]
Closing for now due to lack of response.
